server:
  port: 8081
  
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/moamoa?serverTimezone=Asia/Seoul
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 1111
 jpa:
  database: mysql
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  generate-ddl: true
  show-sql: true

---
  
mybatis:
 type-aliases-package: com.comgongju.moamoa
 config-location: classpath:mybatis/mapper/mybatis-config.xml



